### PR TITLE
Order cancellation

### LINKED ISSUE #130: Refunded / cancelled orders are not cancelled in Magento
If a paid, ready to ship order is imported to Magento, then cancelled on Reverb the Magento Order import will not pick up on the change and will leave the order in a "Processing" (cleared to ship) state

### PR DESCRIPTION
**Pull request by dunagan5887**
Fix #130 

Code to implement cancelling orders via the Reverb Order Update retrieval process

### CODE REVIEW

**Comment by dunagan5887** [comment]
What's the status on this?

**Comment by skwp** [comment]
sorry I haven't had a chance to look at it today, it's been very busy. going to look now thanks for the reminder

**Comment by skwp** [comment]
Got this message while testing on my instance

Exception occurred while executing the status update for order with magento entity id 2 to status cancelled: The Magento system has determined that the Magento order with increment id 000000002 can not be cancelled	

Not sure what's up with the increment id, the order is is actually 235

**Comment by skwp** [comment]
Nothing more in the log except that one message

**Comment by skwp** [comment]
The order in question is in magento "processing" state. is that the problem? http://ec2-54-157-249-149.compute-1.amazonaws.com/index.php/admin/sales_order/view/order_id/2/key/692d8e6dde1e9adb6d2fdb688d9d612c/

**Comment by dunagan5887** [comment]
https://github.com/reverbdotcom/reverb-magento/commit/5914b0e0d7da01c0de055d2ac68f37413c0f7c99

The above commit will give the reason that the order can not be cancelled in that event

**Comment by skwp** [comment]
excellent thank you

**Pull request merged**
