### PR TITLE
Again: "Urlencode sku of product listing.""

### PR DESCRIPTION
**Pull request by skwp**
This is a re-PR of @zztimur 's code

### CODE REVIEW

**Comment by skwp** [comment]
Note: the effect of this code has been to cause the Reverb side sku to be URL encoded. I don't think this is correct. In other words, I typed a sku like "foo bar" on Magento, it comes over as "foo%20bar" in reverb's database. I don't think this is correct. Any url encoding should only be done in transit by the curl adapter. It feels like you double url encoded it

**Comment by skwp** [comment]
cc @zztimur  ^

**Comment by skwp** [comment]
Here's the actual example. In magento I entered a sku: "sku wt

`test1234   with spaces!?`

With your new code the sku in reverb ended up as

`test1234+++with+spaces%21%3F`

With the old code, the sku on reverb ends up correct.

I think you are correctly pointing out _some_ kind of bug here, but I don't think urlencoding the sku at least in the place you've done it is the correct solution.

**Comment by skwp** [comment]
This curl request does not look correct:
curl -i -k -XGET  "X-Reverb-App: magento" "https://sandbox.reverb.com/api/my/listings?state=all&sku=test1234+++with+spaces%21%3F"

**Comment by skwp** [comment]
I'm pretty sure your fix should be to urlencode the GET request but NOT to urlencode the sku in the post to reverb. Post body params do not need to be urlencoded; they are not urls.

**Comment by skwp** [comment]
In other words, the correct implementation would be,

1. when POST/PUT the sku to reverb, use the unencoded sku in the post/put body "sku foo bar"
2. when GET the listing by sku, urlencode the SKU in the GET lookup because urls should be urlencoded. It is more correct to urlencode the entire url than just the sku as you may have spaces in other places.

**Comment by dunagan5887** [comment]
Would it be possible to URL decode the GET request on the Reverb side so that Reverb is storing the expected sku?

**Comment by zztimur** [comment]
@dunagan5887  Yes, that's what I initially thought. I don't know how fast reverb can implement it.

**Comment by skwp** [comment]
I don't think this is an API level responsibility. Some people may legitimately want a "+" in their SKU. There would be no way for us to know whether the sku is url encoded. URL encoding something that clients should _always_ do for GET requests. That really should be done at the curl adapter layer and I'm surprised it's not handled for you.

**Comment by dunagan5887** [comment]
I'll double-check but the cURL adapter is URL encoding the sku, which is what's causing the problem.

During the POST/PUT request the sku is NOT url encoded, so Reverb does not recognize it as existing in the Reverb system.

**Comment by skwp** [comment]
I think we still have a miscommunication here. The sku in the body of PUT/POST should not ever be urlencoded. urlencoding is for urls only, each GET request should be url encoded on the url level, not a per-attribute level

**Comment by skwp** [comment]
Without the zztimur fix to me it looks like everything is correct. The outbound requests based on the log show the sku being urlencoded, which is right. I'm not sure what zztim's fix is fixing

**Comment by dunagan5887** [comment]
> "Some people may legitimately want a "+" in their SKU"

Then the following would be sent for sku "test+1234 with + spaces!?" 

``
"https://sandbox.reverb.com/api/my/listings?state=all&sku=test%2B1234+with+%2B+spaces%21%3F"
``

> "each GET request should be url encoded on the url level, not a per-attribute level"

encoding the entire url would result in the following, which definitely would not resolve correctly

``
https%3A%2F%2Fsandbox.reverb.com%2Fapi%2Fmy%2Flistings%3Fstate%3Dall%26sku%3Dtest%2B1234+with+%2B+spaces%21%3F
``

**Comment by skwp** [comment]
From chatting with timur I think there might be some edge case where certain chars like tabs or other nonprintables might not be handled correctly by the put/post. However I think that's more of a problem with the client's magento data than something we can really handle. Let me know if there's some workaround for that but I'm not sure what to do with a sku that has a tab in it.

**Comment by skwp** [comment]
you might be right about encoding the entire url. I was basing that off of ruby's URI.encode which correctly encodes just the parts that need to be encoded. php's urlencode might not be that smart :)

**Comment by dunagan5887** [comment]
If you run a url decode on whatever is passed in the sku field, this should solve everything. I'm not sure what issues would be caused by this

PHP is better than Ruby :P

**Comment by skwp** [comment]
we can't urldecode because that would turn "sku+foo" into "sku foo". some people use plusses for a reason, or other special chars.

**Comment by dunagan5887** [comment]
So let's say a product's sku is "sku+foo". Then the GET request would communicate "sku%2Bfoo" Running a URL-decode on "sku%2Bfoo" results in "sku+foo" which is the correct sku

**Comment by skwp** [comment]
correct. we already do the urldecode in transit, so everything is working as expected, without zztimur's changes. I am closing this PR for now until we can pinpoint the problem. I think it has to do with nonprintable characters.

**Comment by zztimur** [comment]
why does url request with "sku%9"
doesn't match the product with "sku\t" set in reverb?

On Wed, Apr 27, 2016 at 3:50 PM, Yan Pritzker <notifications@github.com>
wrote:

> Without the zztimur fix to me it looks like everything is correct. The
> outbound requests based on the log show the sku being urlencoded, which is
> right. I'm not sure what zztim's fix is fixing
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/reverbdotcom/reverb-magento/pull/242#issuecomment-215224898>
>



-- 
-- Sent from my iPhone

**Comment by zztimur** [comment]
Safe to assume you guys will be handling this on server side?

**Comment by kylecrum** [comment]
@zztimur why does the sku have an unprintable character in it? That's just a recipe for all kinds of errors. From a UX point of view, someone is searching for their sku in a UI, they would then need to know that there is a tab at the end?

**Comment by skwp** [comment]
@zztimur I just tried to urlencode "sku\t" here http://meyerweb.com/eric/tools/dencoder/ and got sku%5Ct so perhaps the problem is the %9

**Comment by skwp** [comment]
i see that CGI escape produces "sku%09". but "sku%9" is not valid. there should be a 2 digit code there

**Comment by zztimur** [comment]
Kyle, I understand. But magento doesn't validate that, so users put all
sorts of things.



On Wed, Apr 27, 2016 at 4:14 PM, Yan Pritzker <notifications@github.com>
wrote:

> @zztimur <https://github.com/zztimur> I just tried to urlencode "sku\t"
> here http://meyerweb.com/eric/tools/dencoder/ and got sku%5Ct so perhaps
> the problem is the %9
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/reverbdotcom/reverb-magento/pull/242#issuecomment-215231361>
>



-- 
-- Sent from my iPhone

**Pull request closed without merging**
