### PR TITLE
Sync description on update

### PR DESCRIPTION
**Pull request by skwp**
Does not provide support for mass-sync description updates

### CODE REVIEW

**Comment by skwp** [comment]
I hacked this up by following existing patterns. Needs testing

**Comment by skwp** [comment]
No I probably missed something. If you want to finish this up and it's relevant to you guys I would love the help

**Comment by zztimur** [comment]
To Confirm: You expect that updating description would trigger listing update, correct?

**Comment by skwp** [comment]
Correct I would expect the update to any field that matters to trigger a sync including description.

**Comment by skwp** [comment]
Not sure what I need to do to get the description update to trigger. @zztimur any pointers?

**Comment by zztimur** [comment]
I’ll look into that tonight.

**Comment by skwp** [comment]
that would be great. I'd like to bundle this for the next release with the category changes

**Comment by skwp** [comment]
@dunagan5887 would you be able to help take this to the finish line

**Comment by dunagan5887** [comment]
Which version(s) are you guys seeing this issue on? I'm using 1.9 and 1.7, and any time I update only the description field on a product, a listing sync background task is created

**Comment by zztimur** [comment]
1.9.0.1 - updating description doesn't trigger a sync task

**Comment by dunagan5887** [comment]
Does this product have its "Sync to Reverb" field set to "Yes"?

**Comment by zztimur** [comment]
Yes

**Comment by zztimur** [comment]
I have too look into this on our instance

**Comment by dunagan5887** [comment]
I was testing on 1.9.2.0. I can set up an instance of 1.9.0.1 and test if you'd like

**Comment by zztimur** [comment]
It works, the issue was on our end. Thanks

On Tue, Apr 12, 2016 at 11:03 AM, Sean Dunagan <notifications@github.com>
wrote:

> I was testing on 1.9.2.0. I can set up an instance of 1.9.0.1 and test if
> you'd like
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/reverbdotcom/reverb-magento/pull/226#issuecomment-208982414>
>



-- 
-- Sent from my iPhone

**Comment by skwp** [comment]
Do we need to do any handling for a bulk update or is this ok?

**Comment by dunagan5887** [comment]
Bulk updating of the description field doesn't sound like a common occurrence, but I could be wrong

**Comment by skwp** [comment]
Even if not common i'm worried that we support bulk on most fields but not this one so it might be a confusing support issue. related thought: If we implement arbitrary field mapping do we need to somehow support those arbitrary fields being bulk updated also?

**Comment by dunagan5887** [comment]
That sounds like a business question to me. It wouldn't be too hard to tie those fields in to the trigger

**Comment by skwp** [comment]
Sorry to rephrase, I do want everything to be bulk updateable or customers will be confused and come to us for support. I'm just making sure there's not a technical limitation to doing that for our arbitrary mapped fields as well. For this PR, can you please add whatever hooks we need for bulk updates to work? Thanks!

**Comment by skwp** [comment]
I'm going to merge this and wait on bulk support for descriptoin in a separate PR @dunagan5887

**Pull request merged**
