### PR TITLE
Renamed rev_sync attribute to sync_to_reverb for clarity [Fix #115]

### LINKED ISSUE #115: rev_sync attribute should be named sync_to_reverb to be intuitive
Currently the "Sync to Reverb" attribute code is `rev_sync`, which is somewhat unclear.  I'd suggest using `sync_to_reverb` to align with the UI name and to at least make it explicit that it's a Reverb attribute.

### PR DESCRIPTION
**Pull request by StevenWolfe**
Renamed `rev_sync` attribute to `sync_to_reverb` and updated usages

### CODE REVIEW

**Comment by skwp** [comment]
Thanks for the PR! is this safe to apply to existing installatiolns?

**Comment by StevenWolfe** [comment]
No, this won't handle migration.  The installer will need a new script.  I'll be making a few more pull requests with some changes which MSL will need to go live.  This one is trivial, but some are critical.

**Comment by skwp** [comment]
Could you please provide a migration script? This is a little beyond me and I'd like to merge the PR but not if it impacts existing customers negatively.

**Comment by StevenWolfe** [comment]
let's leave this out for now then; the migration isn't relevant to MSL and I'd rather not spend their time on it--it can be migrated in the future.

**Comment by skwp** [comment]
Sounds good thanks. I'll keep this open for a bit to see if our developer can knock this out pretty quickly

**Comment by skwp** [comment]
@dunagan5887 i'm not merging this one because it would require a data migration

**Comment by dunagan5887** [comment]
Agreed, its more cosmetic than it is functional

**Comment by StevenWolfe** [comment]
Closing - Pull #125 includes a migration script and renamed two other `rev_*` attributes

**Pull request closed without merging**
