### PR TITLE
Clear actions on certain Reverb admin sections take you on 404 trip [Fix #215]

### LINKED ISSUE #215: Clear actions on certain Reverb admin sections take you on a 404 trip
In admin panel, Reverb section:
- Reverb->Image Sync->Clear All Tasks - 404 error
- Reverb->Image Sync->Clear Successful Sync Tasks - 404 error
- Reverb->Image Sync->Order Creation and Shipment Tracking->Clear All Tasks - 404 error
- Reverb->Image Sync->Order Creation and Shipment Tracking->Clear Successful Sync Tasks - 404 error
- Reverb->Image Sync->Order Update->Clear All Tasks - 404 error
- Reverb->Image Sync->Order Update->Clear Successful Sync Tasks - 404 error

### PR DESCRIPTION
**Pull request by zztimur**
Resolution for issue #215

### CODE REVIEW

**Comment by zztimur** [comment]
Added code to address the issue #217.

It was really hard to work with all the duplicate code and bugs, where action buttons wouldn't work.
So I took some time to slightly adjust the code for admin controllers.

**Quick overview:**
- There was bunch of redundant logging involved, I removed the duplicates and combined logging for redirect errors in one function.
- IndexAction for controllers extended from ProcessQueue were repetitive. They were pulled up to Reverb/ProcessQueue/controllers/Adminhtml/ProcessQueue/IndexController.php in the _initAction as preparation.
- Same goes for actOnTaskAction. With all those properties per each controller, there's really no need to have that function per each child class.
- return URL parameter on action buttons was implemented so inconsistently and randomly, that I removed it, as there is no case were it's needed.
- pulled some constants to ProcessQueue level. Removed unused ones.

**Comment by skwp** [comment]
thanks! @dunagan5887 could you please give this a quick overview

**Comment by skwp** [comment]
This is a big change so I'll merge but need some time to test

**Comment by dunagan5887** [comment]
Just looked this over and it makes sense. If it has been tested then it looks good to merge to me

**Comment by zztimur** [comment]
I tested it and it does work.

**Pull request merged**
