### PR TITLE
Issues/GitHub 19 image sync

### LINKED ISSUE #19: Image sync
when syncing product listing to reverb, sync all the images. We have no way to delete images right now so if there are issues around figuring out which images have been synced, we can implement some API to wipe out all existing images.

### PR DESCRIPTION
**Pull request by dunagan5887**
Fix #19 

Option B detailed in https://github.com/reverbdotcom/reverb-magento/issues/19 has been implemented on this branch

### CODE REVIEW

**Comment by skwp** [comment]
So is this only  syncing one image?

**Comment by dunagan5887** [comment]
Currently yes. I can update it to post every image on the product if you'd like

**Comment by skwp** [comment]
Yes I'd like it to post all the images. Is this only done on first time create?

**Comment by skwp** [comment]
We only want this to happen on initial listing create. If it's an update, we need a check for when we last synced images and to determine if any images are new since that point. if that's hard to do we can omit for now

**Comment by dunagan5887** [comment]
going to update the code to include all gallery images on both create and update calls

**Comment by skwp** [comment]
Thanks. pls see chatter in magento chat room, on update we want to check for timestamps or we'll end up with dupe images

**Comment by skwp** [comment]
closing until we have the uniqueness checks in place

**Pull request closed without merging**
