### PR TITLE
Clear indication of tasks completed/failed/retrying

### PR DESCRIPTION
**Pull request by skwp**

### CODE REVIEW

**Comment by skwp** [comment]
@dunagan5887 the css file seems blank?

**Comment by dunagan5887** [comment]
Correct, I wasn't able to do any styling before I had to run out last night, which is why I didn't create a pull request. I can take care of the styling if or you can put your own personal touch on it if you'd like

**Comment by dunagan5887** [comment]
Added some basic table styling to the status tasks; I've never advertised myself as a designer or an artist. This is ready to merge as long as it looks good to you

**Comment by dunagan5887** [comment]
I accidentally added Fix #55  to this branch, sorry about that. They are fine to merge together though.

**Pull request merged**
