### PR TITLE
Make/model dropdown mapping

### PR DESCRIPTION
**Pull request by skwp**
I think this broke the make/model mapping so I'm leaving it in PR until we test it more thoroughly

### CODE REVIEW

**Comment by skwp** [comment]
@zztimur this is your PR. I feel like it might have broken something (no make/model fields coming across at all). So i'm reverting in master while I test

**Comment by skwp** [comment]
@zztimur strange both with and without this PR i'm not seeing make/model information being sent over. are you seeing it in your logs?

**Comment by zztimur** [comment]
let me check what's going on. Which version of magenta are you on?

**Comment by zztimur** [comment]
Works both on 1.9 and 1.7

**Pull request merged**
