### PR TITLE
Category UUID Support

### LINKED ISSUE #223: Migration to backfill category UUIDs
Reverb is changing its category system to be UUID based. This will enable us to change category  names and slugs without affecting customer category mappings. The API will update as follows:

**Before:**
product_type_slug:"foo"
categories:["something","something-else"]

**After:**
category_uuids: ["1234-asdf-1234-1324"]

In order to support this change, we'll need to do a migration to attach a UUID to every category that's in the database. A CSV file will be supplied that will look like this:

original_product_type_slug, original_category_slug, uuid
electric-guitars, 12-string, 1234-5678-1234-5678

This file should become the source of truth for magento categories. Therefore:

1. Change code that ties magento categories to reverb categories in the database to do it by UUID to tie them to the text file.

2. Provide a migration so that the mappings already in place move to point to the text file by looking up each mapping via product_type_slug and category_slug in the file and adding the UUID to the database.

### PR DESCRIPTION
**Pull request by dunagan5887**
Fix #223

### CODE REVIEW

**Comment by skwp** [comment]
Can we get rid of the CSV stuff now?

**Comment by dunagan5887** [comment]
The CSV stuff is being used by the initial migration which updates the Reverb category list. Are you saying you want to modify that migration script to use the new JSON API functionality?

**Comment by skwp** [comment]
Yes the JSON api should be the source of truth for everything

**Comment by dunagan5887** [comment]
The migration script is now based off of the API JSON data response. I removed all architecture related to the CSV file parsing. In terms of clients, I would recommend that they perform this update in maintenance mode during off hours just to be safe. I wrapped everything in try-catch blocks, but who knows what third-party extensions people have loaded on their instances

**Pull request merged**
