### PR TITLE
Import orders using the default Store [Fix #126]

### LINKED ISSUE #126: Imported orders are created under "Admin" Store View instead of default Store View
Reverb's imported orders are being created under the "Admin / Default / Admin" Store View (visible in the Order's "Purchased From" field).  Our orders are normally created under "Main Website / Main Website Store / Default Store View".

This has the effect of assigning the orders different order and invoice numbers.  Such as "000000102" rather than the expected "100041655".  This appears to have some impact on other third-party modules as well, although it appears relatively benign.

### PR DESCRIPTION
**Pull request by StevenWolfe**
Import orders to the default Store (not configurable, but likely a sane default).  Quotes / Orders / Invoices will use the normal increment id.

### CODE REVIEW

**Comment by dunagan5887** [comment]
This looks good for an installation which still has 'default' as the store code for the default store

**Comment by skwp** [comment]
I'd like to make this configurable, so I might let this PR sit for a bit until we can do that

**Comment by StevenWolfe** [comment]
Sounds good, I'll dig in deeper, haven't had as much time as I'd  hoped

**Comment by StevenWolfe** [comment]
This has been updated to use the first non-Admin store id rather than expecting a store with 'default' as its code.  This should be sufficient for single-store installations; and falls back to the Admin store just to be paranoid.

**Comment by dunagan5887** [comment]
This looks good to me, just tested it locally and it worked

**Pull request merged**
